// flow-typed signature: 4180c3dc9e7d3fa8872f2a501610cb85
// flow-typed version: <<STUB>>/react-uwp_v^1.2.2/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-uwp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-uwp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-uwp/__Mock__/index' {
  declare module.exports: any;
}

declare module 'react-uwp/Animate/CustomAnimate' {
  declare module.exports: any;
}

declare module 'react-uwp/Animate/CustomAnimateChild' {
  declare module.exports: any;
}

declare module 'react-uwp/Animate/FadeInOut' {
  declare module.exports: any;
}

declare module 'react-uwp/Animate/index' {
  declare module.exports: any;
}

declare module 'react-uwp/Animate/ScaleInOut' {
  declare module.exports: any;
}

declare module 'react-uwp/Animate/SlideInOut' {
  declare module.exports: any;
}

declare module 'react-uwp/AppBarButton/index' {
  declare module.exports: any;
}

declare module 'react-uwp/AppBarSeparator/index' {
  declare module.exports: any;
}

declare module 'react-uwp/AutoSuggestBox/index' {
  declare module.exports: any;
}

declare module 'react-uwp/Button/index' {
  declare module.exports: any;
}

declare module 'react-uwp/CalendarDatePicker/index' {
  declare module.exports: any;
}

declare module 'react-uwp/CalendarView/DayPicker' {
  declare module.exports: any;
}

declare module 'react-uwp/CalendarView/FadeInOut' {
  declare module.exports: any;
}

declare module 'react-uwp/CalendarView/FadeInOutChild' {
  declare module.exports: any;
}

declare module 'react-uwp/CalendarView/index' {
  declare module.exports: any;
}

declare module 'react-uwp/CalendarView/MonthPicker' {
  declare module.exports: any;
}

declare module 'react-uwp/CalendarView/ScaleInOut' {
  declare module.exports: any;
}

declare module 'react-uwp/CalendarView/ScaleInOutChild' {
  declare module.exports: any;
}

declare module 'react-uwp/CalendarView/SlideInOut' {
  declare module.exports: any;
}

declare module 'react-uwp/CalendarView/SlideInOutChild' {
  declare module.exports: any;
}

declare module 'react-uwp/CalendarView/YearPicker' {
  declare module.exports: any;
}

declare module 'react-uwp/CheckBox/index' {
  declare module.exports: any;
}

declare module 'react-uwp/ColorPicker/index' {
  declare module.exports: any;
}

declare module 'react-uwp/CommandBar/index' {
  declare module.exports: any;
}

declare module 'react-uwp/common/addArrayEvent' {
  declare module.exports: any;
}

declare module 'react-uwp/common/AddBlurEvent' {
  declare module.exports: any;
}

declare module 'react-uwp/common/addEventListener' {
  declare module.exports: any;
}

declare module 'react-uwp/common/addWarning' {
  declare module.exports: any;
}

declare module 'react-uwp/common/animation' {
  declare module.exports: any;
}

declare module 'react-uwp/common/browser/addCSSRule' {
  declare module.exports: any;
}

declare module 'react-uwp/common/browser/isSupportWebP' {
  declare module.exports: any;
}

declare module 'react-uwp/common/browser/scrollToYEasing' {
  declare module.exports: any;
}

declare module 'react-uwp/common/browser/vendors' {
  declare module.exports: any;
}

declare module 'react-uwp/common/createMergeFuncs' {
  declare module.exports: any;
}

declare module 'react-uwp/common/date.utils' {
  declare module.exports: any;
}

declare module 'react-uwp/common/easing' {
  declare module.exports: any;
}

declare module 'react-uwp/common/electron/IS_ELECTRON_ENV' {
  declare module.exports: any;
}

declare module 'react-uwp/common/getComputedStyle' {
  declare module.exports: any;
}

declare module 'react-uwp/common/hex2hsl' {
  declare module.exports: any;
}

declare module 'react-uwp/common/hex2rgb' {
  declare module.exports: any;
}

declare module 'react-uwp/common/nodeJS/IS_NODE_ENV' {
  declare module.exports: any;
}

declare module 'react-uwp/common/prefixAll' {
  declare module.exports: any;
}

declare module 'react-uwp/common/react/isUnitlessNumber' {
  declare module.exports: any;
}

declare module 'react-uwp/common/removeArrayEvent' {
  declare module.exports: any;
}

declare module 'react-uwp/common/removeEventListener' {
  declare module.exports: any;
}

declare module 'react-uwp/common/rgb2hsl' {
  declare module.exports: any;
}

declare module 'react-uwp/common/setStyleToElement' {
  declare module.exports: any;
}

declare module 'react-uwp/common/shallowEqual' {
  declare module.exports: any;
}

declare module 'react-uwp/common/spreadObject' {
  declare module.exports: any;
}

declare module 'react-uwp/ContentDialog/index' {
  declare module.exports: any;
}

declare module 'react-uwp/DatePicker/index' {
  declare module.exports: any;
}

declare module 'react-uwp/Dialog/index' {
  declare module.exports: any;
}

declare module 'react-uwp/DropDownMenu/index' {
  declare module.exports: any;
}

declare module 'react-uwp/ElementState' {
  declare module.exports: any;
}

declare module 'react-uwp/FlipView/Dots' {
  declare module.exports: any;
}

declare module 'react-uwp/FlipView/index' {
  declare module.exports: any;
}

declare module 'react-uwp/FloatNav/index' {
  declare module.exports: any;
}

declare module 'react-uwp/Flyout/index' {
  declare module.exports: any;
}

declare module 'react-uwp/FlyoutContent/index' {
  declare module.exports: any;
}

declare module 'react-uwp/HyperLink/index' {
  declare module.exports: any;
}

declare module 'react-uwp/Icon/icons' {
  declare module.exports: any;
}

declare module 'react-uwp/Icon/index' {
  declare module.exports: any;
}

declare module 'react-uwp/IconButton/index' {
  declare module.exports: any;
}

declare module 'react-uwp/Image/index' {
  declare module.exports: any;
}

declare module 'react-uwp/Link/index' {
  declare module.exports: any;
}

declare module 'react-uwp/ListView/index' {
  declare module.exports: any;
}

declare module 'react-uwp/MarkdownRender/index' {
  declare module.exports: any;
}

declare module 'react-uwp/MarkdownRender/prismCoyCSS' {
  declare module.exports: any;
}

declare module 'react-uwp/MarkdownRender/prismOkaidiaCSS' {
  declare module.exports: any;
}

declare module 'react-uwp/MediaPlayer/Control' {
  declare module.exports: any;
}

declare module 'react-uwp/MediaPlayer/index' {
  declare module.exports: any;
}

declare module 'react-uwp/Menu/index' {
  declare module.exports: any;
}

declare module 'react-uwp/Menu/MenuItem' {
  declare module.exports: any;
}

declare module 'react-uwp/NavigationView/index' {
  declare module.exports: any;
}

declare module 'react-uwp/PasswordBox/index' {
  declare module.exports: any;
}

declare module 'react-uwp/ProgressBar/index' {
  declare module.exports: any;
}

declare module 'react-uwp/ProgressRing/index' {
  declare module.exports: any;
}

declare module 'react-uwp/PseudoClasses' {
  declare module.exports: any;
}

declare module 'react-uwp/RadioButton/index' {
  declare module.exports: any;
}

declare module 'react-uwp/RatingControl/index' {
  declare module.exports: any;
}

declare module 'react-uwp/RenderToBody' {
  declare module.exports: any;
}

declare module 'react-uwp/ScrollBar/index' {
  declare module.exports: any;
}

declare module 'react-uwp/ScrollReveal/index' {
  declare module.exports: any;
}

declare module 'react-uwp/SemanticZoom/index' {
  declare module.exports: any;
}

declare module 'react-uwp/Separator/index' {
  declare module.exports: any;
}

declare module 'react-uwp/Slider/index' {
  declare module.exports: any;
}

declare module 'react-uwp/SplitView/index' {
  declare module.exports: any;
}

declare module 'react-uwp/SplitView/SplitViewPane' {
  declare module.exports: any;
}

declare module 'react-uwp/SplitViewCommand/index' {
  declare module.exports: any;
}

declare module 'react-uwp/styles/accentColors' {
  declare module.exports: any;
}

declare module 'react-uwp/styles/darkTheme' {
  declare module.exports: any;
}

declare module 'react-uwp/styles/fonts/segoe-mdl2-assets/index' {
  declare module.exports: any;
}

declare module 'react-uwp/styles/generateAcrylicTexture' {
  declare module.exports: any;
}

declare module 'react-uwp/styles/getStripedBackground' {
  declare module.exports: any;
}

declare module 'react-uwp/styles/getTheme' {
  declare module.exports: any;
}

declare module 'react-uwp/styles/lightTheme' {
  declare module.exports: any;
}

declare module 'react-uwp/styles/StyleManager' {
  declare module.exports: any;
}

declare module 'react-uwp/Swipe/index' {
  declare module.exports: any;
}

declare module 'react-uwp/Tabs/index' {
  declare module.exports: any;
}

declare module 'react-uwp/Tabs/Tab' {
  declare module.exports: any;
}

declare module 'react-uwp/TextBox/index' {
  declare module.exports: any;
}

declare module 'react-uwp/Theme/getBaseCSSText' {
  declare module.exports: any;
}

declare module 'react-uwp/Theme/index' {
  declare module.exports: any;
}

declare module 'react-uwp/TimePicker/index' {
  declare module.exports: any;
}

declare module 'react-uwp/Toast/index' {
  declare module.exports: any;
}

declare module 'react-uwp/Toast/ToastWrapper' {
  declare module.exports: any;
}

declare module 'react-uwp/Toggle/index' {
  declare module.exports: any;
}

declare module 'react-uwp/Tooltip/index' {
  declare module.exports: any;
}

declare module 'react-uwp/TransformCard/index' {
  declare module.exports: any;
}

declare module 'react-uwp/TreeView/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-uwp/__Mock__/index.js' {
  declare module.exports: $Exports<'react-uwp/__Mock__/index'>;
}
declare module 'react-uwp/Animate/CustomAnimate.js' {
  declare module.exports: $Exports<'react-uwp/Animate/CustomAnimate'>;
}
declare module 'react-uwp/Animate/CustomAnimateChild.js' {
  declare module.exports: $Exports<'react-uwp/Animate/CustomAnimateChild'>;
}
declare module 'react-uwp/Animate/FadeInOut.js' {
  declare module.exports: $Exports<'react-uwp/Animate/FadeInOut'>;
}
declare module 'react-uwp/Animate/index.js' {
  declare module.exports: $Exports<'react-uwp/Animate/index'>;
}
declare module 'react-uwp/Animate/ScaleInOut.js' {
  declare module.exports: $Exports<'react-uwp/Animate/ScaleInOut'>;
}
declare module 'react-uwp/Animate/SlideInOut.js' {
  declare module.exports: $Exports<'react-uwp/Animate/SlideInOut'>;
}
declare module 'react-uwp/AppBarButton/index.js' {
  declare module.exports: $Exports<'react-uwp/AppBarButton/index'>;
}
declare module 'react-uwp/AppBarSeparator/index.js' {
  declare module.exports: $Exports<'react-uwp/AppBarSeparator/index'>;
}
declare module 'react-uwp/AutoSuggestBox/index.js' {
  declare module.exports: $Exports<'react-uwp/AutoSuggestBox/index'>;
}
declare module 'react-uwp/Button/index.js' {
  declare module.exports: $Exports<'react-uwp/Button/index'>;
}
declare module 'react-uwp/CalendarDatePicker/index.js' {
  declare module.exports: $Exports<'react-uwp/CalendarDatePicker/index'>;
}
declare module 'react-uwp/CalendarView/DayPicker.js' {
  declare module.exports: $Exports<'react-uwp/CalendarView/DayPicker'>;
}
declare module 'react-uwp/CalendarView/FadeInOut.js' {
  declare module.exports: $Exports<'react-uwp/CalendarView/FadeInOut'>;
}
declare module 'react-uwp/CalendarView/FadeInOutChild.js' {
  declare module.exports: $Exports<'react-uwp/CalendarView/FadeInOutChild'>;
}
declare module 'react-uwp/CalendarView/index.js' {
  declare module.exports: $Exports<'react-uwp/CalendarView/index'>;
}
declare module 'react-uwp/CalendarView/MonthPicker.js' {
  declare module.exports: $Exports<'react-uwp/CalendarView/MonthPicker'>;
}
declare module 'react-uwp/CalendarView/ScaleInOut.js' {
  declare module.exports: $Exports<'react-uwp/CalendarView/ScaleInOut'>;
}
declare module 'react-uwp/CalendarView/ScaleInOutChild.js' {
  declare module.exports: $Exports<'react-uwp/CalendarView/ScaleInOutChild'>;
}
declare module 'react-uwp/CalendarView/SlideInOut.js' {
  declare module.exports: $Exports<'react-uwp/CalendarView/SlideInOut'>;
}
declare module 'react-uwp/CalendarView/SlideInOutChild.js' {
  declare module.exports: $Exports<'react-uwp/CalendarView/SlideInOutChild'>;
}
declare module 'react-uwp/CalendarView/YearPicker.js' {
  declare module.exports: $Exports<'react-uwp/CalendarView/YearPicker'>;
}
declare module 'react-uwp/CheckBox/index.js' {
  declare module.exports: $Exports<'react-uwp/CheckBox/index'>;
}
declare module 'react-uwp/ColorPicker/index.js' {
  declare module.exports: $Exports<'react-uwp/ColorPicker/index'>;
}
declare module 'react-uwp/CommandBar/index.js' {
  declare module.exports: $Exports<'react-uwp/CommandBar/index'>;
}
declare module 'react-uwp/common/addArrayEvent.js' {
  declare module.exports: $Exports<'react-uwp/common/addArrayEvent'>;
}
declare module 'react-uwp/common/AddBlurEvent.js' {
  declare module.exports: $Exports<'react-uwp/common/AddBlurEvent'>;
}
declare module 'react-uwp/common/addEventListener.js' {
  declare module.exports: $Exports<'react-uwp/common/addEventListener'>;
}
declare module 'react-uwp/common/addWarning.js' {
  declare module.exports: $Exports<'react-uwp/common/addWarning'>;
}
declare module 'react-uwp/common/animation.js' {
  declare module.exports: $Exports<'react-uwp/common/animation'>;
}
declare module 'react-uwp/common/browser/addCSSRule.js' {
  declare module.exports: $Exports<'react-uwp/common/browser/addCSSRule'>;
}
declare module 'react-uwp/common/browser/isSupportWebP.js' {
  declare module.exports: $Exports<'react-uwp/common/browser/isSupportWebP'>;
}
declare module 'react-uwp/common/browser/scrollToYEasing.js' {
  declare module.exports: $Exports<'react-uwp/common/browser/scrollToYEasing'>;
}
declare module 'react-uwp/common/browser/vendors.js' {
  declare module.exports: $Exports<'react-uwp/common/browser/vendors'>;
}
declare module 'react-uwp/common/createMergeFuncs.js' {
  declare module.exports: $Exports<'react-uwp/common/createMergeFuncs'>;
}
declare module 'react-uwp/common/date.utils.js' {
  declare module.exports: $Exports<'react-uwp/common/date.utils'>;
}
declare module 'react-uwp/common/easing.js' {
  declare module.exports: $Exports<'react-uwp/common/easing'>;
}
declare module 'react-uwp/common/electron/IS_ELECTRON_ENV.js' {
  declare module.exports: $Exports<'react-uwp/common/electron/IS_ELECTRON_ENV'>;
}
declare module 'react-uwp/common/getComputedStyle.js' {
  declare module.exports: $Exports<'react-uwp/common/getComputedStyle'>;
}
declare module 'react-uwp/common/hex2hsl.js' {
  declare module.exports: $Exports<'react-uwp/common/hex2hsl'>;
}
declare module 'react-uwp/common/hex2rgb.js' {
  declare module.exports: $Exports<'react-uwp/common/hex2rgb'>;
}
declare module 'react-uwp/common/nodeJS/IS_NODE_ENV.js' {
  declare module.exports: $Exports<'react-uwp/common/nodeJS/IS_NODE_ENV'>;
}
declare module 'react-uwp/common/prefixAll.js' {
  declare module.exports: $Exports<'react-uwp/common/prefixAll'>;
}
declare module 'react-uwp/common/react/isUnitlessNumber.js' {
  declare module.exports: $Exports<'react-uwp/common/react/isUnitlessNumber'>;
}
declare module 'react-uwp/common/removeArrayEvent.js' {
  declare module.exports: $Exports<'react-uwp/common/removeArrayEvent'>;
}
declare module 'react-uwp/common/removeEventListener.js' {
  declare module.exports: $Exports<'react-uwp/common/removeEventListener'>;
}
declare module 'react-uwp/common/rgb2hsl.js' {
  declare module.exports: $Exports<'react-uwp/common/rgb2hsl'>;
}
declare module 'react-uwp/common/setStyleToElement.js' {
  declare module.exports: $Exports<'react-uwp/common/setStyleToElement'>;
}
declare module 'react-uwp/common/shallowEqual.js' {
  declare module.exports: $Exports<'react-uwp/common/shallowEqual'>;
}
declare module 'react-uwp/common/spreadObject.js' {
  declare module.exports: $Exports<'react-uwp/common/spreadObject'>;
}
declare module 'react-uwp/ContentDialog/index.js' {
  declare module.exports: $Exports<'react-uwp/ContentDialog/index'>;
}
declare module 'react-uwp/DatePicker/index.js' {
  declare module.exports: $Exports<'react-uwp/DatePicker/index'>;
}
declare module 'react-uwp/Dialog/index.js' {
  declare module.exports: $Exports<'react-uwp/Dialog/index'>;
}
declare module 'react-uwp/DropDownMenu/index.js' {
  declare module.exports: $Exports<'react-uwp/DropDownMenu/index'>;
}
declare module 'react-uwp/ElementState.js' {
  declare module.exports: $Exports<'react-uwp/ElementState'>;
}
declare module 'react-uwp/FlipView/Dots.js' {
  declare module.exports: $Exports<'react-uwp/FlipView/Dots'>;
}
declare module 'react-uwp/FlipView/index.js' {
  declare module.exports: $Exports<'react-uwp/FlipView/index'>;
}
declare module 'react-uwp/FloatNav/index.js' {
  declare module.exports: $Exports<'react-uwp/FloatNav/index'>;
}
declare module 'react-uwp/Flyout/index.js' {
  declare module.exports: $Exports<'react-uwp/Flyout/index'>;
}
declare module 'react-uwp/FlyoutContent/index.js' {
  declare module.exports: $Exports<'react-uwp/FlyoutContent/index'>;
}
declare module 'react-uwp/HyperLink/index.js' {
  declare module.exports: $Exports<'react-uwp/HyperLink/index'>;
}
declare module 'react-uwp/Icon/icons.js' {
  declare module.exports: $Exports<'react-uwp/Icon/icons'>;
}
declare module 'react-uwp/Icon/index.js' {
  declare module.exports: $Exports<'react-uwp/Icon/index'>;
}
declare module 'react-uwp/IconButton/index.js' {
  declare module.exports: $Exports<'react-uwp/IconButton/index'>;
}
declare module 'react-uwp/Image/index.js' {
  declare module.exports: $Exports<'react-uwp/Image/index'>;
}
declare module 'react-uwp/index' {
  declare module.exports: $Exports<'react-uwp'>;
}
declare module 'react-uwp/index.js' {
  declare module.exports: $Exports<'react-uwp'>;
}
declare module 'react-uwp/Link/index.js' {
  declare module.exports: $Exports<'react-uwp/Link/index'>;
}
declare module 'react-uwp/ListView/index.js' {
  declare module.exports: $Exports<'react-uwp/ListView/index'>;
}
declare module 'react-uwp/MarkdownRender/index.js' {
  declare module.exports: $Exports<'react-uwp/MarkdownRender/index'>;
}
declare module 'react-uwp/MarkdownRender/prismCoyCSS.js' {
  declare module.exports: $Exports<'react-uwp/MarkdownRender/prismCoyCSS'>;
}
declare module 'react-uwp/MarkdownRender/prismOkaidiaCSS.js' {
  declare module.exports: $Exports<'react-uwp/MarkdownRender/prismOkaidiaCSS'>;
}
declare module 'react-uwp/MediaPlayer/Control.js' {
  declare module.exports: $Exports<'react-uwp/MediaPlayer/Control'>;
}
declare module 'react-uwp/MediaPlayer/index.js' {
  declare module.exports: $Exports<'react-uwp/MediaPlayer/index'>;
}
declare module 'react-uwp/Menu/index.js' {
  declare module.exports: $Exports<'react-uwp/Menu/index'>;
}
declare module 'react-uwp/Menu/MenuItem.js' {
  declare module.exports: $Exports<'react-uwp/Menu/MenuItem'>;
}
declare module 'react-uwp/NavigationView/index.js' {
  declare module.exports: $Exports<'react-uwp/NavigationView/index'>;
}
declare module 'react-uwp/PasswordBox/index.js' {
  declare module.exports: $Exports<'react-uwp/PasswordBox/index'>;
}
declare module 'react-uwp/ProgressBar/index.js' {
  declare module.exports: $Exports<'react-uwp/ProgressBar/index'>;
}
declare module 'react-uwp/ProgressRing/index.js' {
  declare module.exports: $Exports<'react-uwp/ProgressRing/index'>;
}
declare module 'react-uwp/PseudoClasses.js' {
  declare module.exports: $Exports<'react-uwp/PseudoClasses'>;
}
declare module 'react-uwp/RadioButton/index.js' {
  declare module.exports: $Exports<'react-uwp/RadioButton/index'>;
}
declare module 'react-uwp/RatingControl/index.js' {
  declare module.exports: $Exports<'react-uwp/RatingControl/index'>;
}
declare module 'react-uwp/RenderToBody.js' {
  declare module.exports: $Exports<'react-uwp/RenderToBody'>;
}
declare module 'react-uwp/ScrollBar/index.js' {
  declare module.exports: $Exports<'react-uwp/ScrollBar/index'>;
}
declare module 'react-uwp/ScrollReveal/index.js' {
  declare module.exports: $Exports<'react-uwp/ScrollReveal/index'>;
}
declare module 'react-uwp/SemanticZoom/index.js' {
  declare module.exports: $Exports<'react-uwp/SemanticZoom/index'>;
}
declare module 'react-uwp/Separator/index.js' {
  declare module.exports: $Exports<'react-uwp/Separator/index'>;
}
declare module 'react-uwp/Slider/index.js' {
  declare module.exports: $Exports<'react-uwp/Slider/index'>;
}
declare module 'react-uwp/SplitView/index.js' {
  declare module.exports: $Exports<'react-uwp/SplitView/index'>;
}
declare module 'react-uwp/SplitView/SplitViewPane.js' {
  declare module.exports: $Exports<'react-uwp/SplitView/SplitViewPane'>;
}
declare module 'react-uwp/SplitViewCommand/index.js' {
  declare module.exports: $Exports<'react-uwp/SplitViewCommand/index'>;
}
declare module 'react-uwp/styles/accentColors.js' {
  declare module.exports: $Exports<'react-uwp/styles/accentColors'>;
}
declare module 'react-uwp/styles/darkTheme.js' {
  declare module.exports: $Exports<'react-uwp/styles/darkTheme'>;
}
declare module 'react-uwp/styles/fonts/segoe-mdl2-assets/index.js' {
  declare module.exports: $Exports<'react-uwp/styles/fonts/segoe-mdl2-assets/index'>;
}
declare module 'react-uwp/styles/generateAcrylicTexture.js' {
  declare module.exports: $Exports<'react-uwp/styles/generateAcrylicTexture'>;
}
declare module 'react-uwp/styles/getStripedBackground.js' {
  declare module.exports: $Exports<'react-uwp/styles/getStripedBackground'>;
}
declare module 'react-uwp/styles/getTheme.js' {
  declare module.exports: $Exports<'react-uwp/styles/getTheme'>;
}
declare module 'react-uwp/styles/lightTheme.js' {
  declare module.exports: $Exports<'react-uwp/styles/lightTheme'>;
}
declare module 'react-uwp/styles/StyleManager.js' {
  declare module.exports: $Exports<'react-uwp/styles/StyleManager'>;
}
declare module 'react-uwp/Swipe/index.js' {
  declare module.exports: $Exports<'react-uwp/Swipe/index'>;
}
declare module 'react-uwp/Tabs/index.js' {
  declare module.exports: $Exports<'react-uwp/Tabs/index'>;
}
declare module 'react-uwp/Tabs/Tab.js' {
  declare module.exports: $Exports<'react-uwp/Tabs/Tab'>;
}
declare module 'react-uwp/TextBox/index.js' {
  declare module.exports: $Exports<'react-uwp/TextBox/index'>;
}
declare module 'react-uwp/Theme/getBaseCSSText.js' {
  declare module.exports: $Exports<'react-uwp/Theme/getBaseCSSText'>;
}
declare module 'react-uwp/Theme/index.js' {
  declare module.exports: $Exports<'react-uwp/Theme/index'>;
}
declare module 'react-uwp/TimePicker/index.js' {
  declare module.exports: $Exports<'react-uwp/TimePicker/index'>;
}
declare module 'react-uwp/Toast/index.js' {
  declare module.exports: $Exports<'react-uwp/Toast/index'>;
}
declare module 'react-uwp/Toast/ToastWrapper.js' {
  declare module.exports: $Exports<'react-uwp/Toast/ToastWrapper'>;
}
declare module 'react-uwp/Toggle/index.js' {
  declare module.exports: $Exports<'react-uwp/Toggle/index'>;
}
declare module 'react-uwp/Tooltip/index.js' {
  declare module.exports: $Exports<'react-uwp/Tooltip/index'>;
}
declare module 'react-uwp/TransformCard/index.js' {
  declare module.exports: $Exports<'react-uwp/TransformCard/index'>;
}
declare module 'react-uwp/TreeView/index.js' {
  declare module.exports: $Exports<'react-uwp/TreeView/index'>;
}
